services:
  backend:
    image: 651767347273.dkr.ecr.ap-south-1.amazonaws.com/shriaaum/namaha-web:${VERSION}
    container_name: namaha-web
    restart: always
    ports:
      - "3001:8080"
    env_file:
      - .env
