name: frontend build push deploy

on:
  push:
    branches:
      - live
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.ECR_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.ECR_AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region ap-south-1 \
          | docker login --username AWS --password-stdin 651767347273.dkr.ecr.ap-south-1.amazonaws.com

      - name: Set version
        run: echo "VERSION=${GITHUB_SHA::7}" >> $GITHUB_ENV


      - name: Build Web
        run: |
          docker build --no-cache -t namaha-web:$VERSION .
          docker tag namaha-web:$VERSION 651767347273.dkr.ecr.ap-south-1.amazonaws.com/shriaaum/namaha-web:$VERSION
          docker push 651767347273.dkr.ecr.ap-south-1.amazonaws.com/shriaaum/namaha-web:$VERSION
    #       echo "VERSION=$VERSION" > .env.deploy

    #   - name: Setup SSH
    #     uses: webfactory/ssh-agent@v0.9.0
    #     with:
    #       ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    #   - name: Deploy Web
    #     run: |
    #       scp -o StrictHostKeyChecking=no .env.deploy docker-compose.yml ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/lib/projects/namaha-web/
    #       ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << EOF
    #         set -e
    #         cd /var/lib/projects/namaha-web
    #         sudo docker system prune -af
    #         export AWS_REGION=ap-south-1
    #         export ECR_REGISTRY=651767347273.dkr.ecr.ap-south-1.amazonaws.com
    #         echo \$(aws ecr get-login-password --region \$AWS_REGION) | sudo docker login --username AWS --password-stdin \$ECR_REGISTRY
    #         sudo docker compose --env-file .env.deploy up -d
    #       EOF